# Generated by Django 4.2.25 on 2025-10-12 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_packagingtype_materialgroup_customergroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='title',
        ),
        migrations.AddField(
            model_name='quote',
            name='amendment_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='assembly_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='client_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='core.customergroup'),
        ),
        migrations.AddField(
            model_name='quote',
            name='client_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='moulding_machine_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(default='', help_text='Quote name/title', max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='packaging_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='part_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='part_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_definition_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='raw_material_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='sap_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='SAP Number'),
        ),
        migrations.AddField(
            model_name='quote',
            name='transport_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assemblytype',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='assemblytype',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assemblytype',
            name='value',
            field=models.CharField(default='', help_text='Unique identifier/code', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='value',
            field=models.CharField(default='', help_text='Unique identifier/code', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='value',
            field=models.CharField(default='', help_text='Unique identifier/code', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='value',
            field=models.CharField(default='', help_text='Unique identifier/code', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='incomplete', max_length=20),
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(default='', max_length=200)),
                ('grade', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rm_code', models.CharField(default='', max_length=100, verbose_name='RM Code')),
                ('unit_of_measurement', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('ton', 'Ton'), ('lb', 'Pound (lb)')], default='kg', max_length=20)),
                ('frozen_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('rm_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RM Rate')),
                ('part_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('runner_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10)),
                ('process_losses', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10)),
                ('purging_loss_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rm_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('icc_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ICC %')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.materialgroup')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='core.quote')),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
                'ordering': ['created_at'],
            },
        ),
    ]
