# Generated by Django 4.2.25 on 2025-10-12 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_quote_amount_remove_quote_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouldingMachineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavity', models.IntegerField(default=0, help_text='Number of cavities')),
                ('machine_tonnage', models.DecimalField(decimal_places=2, default=0, help_text='Machine tonnage', max_digits=10)),
                ('shift_rate', models.DecimalField(decimal_places=2, default=0, help_text='Shift rate', max_digits=10)),
                ('number_of_mtc', models.IntegerField(default=0, help_text='Number of MTC', verbose_name='Number of MTC')),
                ('shift_rate_for_mtc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shift Rate for MTC')),
                ('mtc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MTC Cost')),
                ('cycle_time', models.DecimalField(decimal_places=2, default=0, help_text='Cycle time in seconds', max_digits=10)),
                ('efficiency', models.DecimalField(decimal_places=2, default=0, help_text='Efficiency percentage', max_digits=5)),
                ('number_of_parts_per_shift', models.IntegerField(default=0, editable=False, help_text='Calculated: Number of parts per shift')),
                ('conversion_cost', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculated: Conversion cost', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moulding_machines', to='core.quote')),
            ],
            options={
                'verbose_name': 'Moulding Machine Detail',
                'verbose_name_plural': 'Moulding Machine Details',
                'ordering': ['created_at'],
            },
        ),
    ]
