# Generated by Django 4.2.25 on 2025-10-12 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mouldingmachinedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_type', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='manual', max_length=20)),
                ('manual_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost for manual assembly', max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Profit percentage', max_digits=5)),
                ('rejection_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Rejection percentage', max_digits=5)),
                ('inspection_handling_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Inspection + Handling percentage', max_digits=5)),
                ('total_assembly_rm_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_manufacturing_printing_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('profit_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('rejection_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('inspection_handling_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_assembly_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly_type_config', models.ForeignKey(blank=True, help_text='Assembly type from configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assemblytype')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='core.quote')),
            ],
            options={
                'verbose_name': 'Assembly',
                'verbose_name_plural': 'Assemblies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingPrintingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(default='', help_text='Process name/description', max_length=200)),
                ('mc_tonnage', models.DecimalField(decimal_places=2, default=0, help_text='Machine tonnage', max_digits=10, verbose_name='M/C Tonnage')),
                ('mc_rate_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='Machine rate per hour', max_digits=10, verbose_name='M/C Rate/Hr')),
                ('cycle_time', models.DecimalField(decimal_places=2, default=0, help_text='Cycle time in seconds', max_digits=10)),
                ('per_cost', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='(Rate/Hr × Cycle Time) / 3600', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_printing_costs', to='core.assembly')),
            ],
            options={
                'verbose_name': 'Manufacturing/Printing Cost',
                'verbose_name_plural': 'Manufacturing/Printing Costs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('production_quantity', models.IntegerField(default=1, help_text='Production quantity')),
                ('production_weight', models.DecimalField(decimal_places=3, default=0, help_text='Production weight/amount', max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('piece', 'Piece'), ('meter', 'Meter (m)'), ('liter', 'Liter (L)')], default='kg', max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='(Production Weight × Cost/Unit) / Production Quantity', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_raw_materials', to='core.assembly')),
            ],
            options={
                'verbose_name': 'Assembly Raw Material',
                'verbose_name_plural': 'Assembly Raw Materials',
                'ordering': ['created_at'],
            },
        ),
    ]
