# Generated by Django 4.2.25 on 2025-10-12 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assembly_manufacturingprintingcost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_type', models.CharField(choices=[('pp_box', 'PP Box'), ('pp_box_partition', 'PP Box with Partition'), ('cg_box', 'CG Box'), ('bin', 'Bin')], default='pp_box', max_length=30)),
                ('length', models.DecimalField(decimal_places=2, default=600, editable=False, max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, default=400, editable=False, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=250, editable=False, max_digits=10)),
                ('polybag_length', models.DecimalField(decimal_places=2, default=16, editable=False, max_digits=10)),
                ('polybag_width', models.DecimalField(decimal_places=2, default=20, editable=False, max_digits=10)),
                ('lifecycle', models.IntegerField(default=0, help_text='Lifecycle count')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Base cost', max_digits=10)),
                ('maintenance_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Maintenance percentage', max_digits=5)),
                ('part_per_polybag', models.IntegerField(default=1, help_text='Number of parts per polybag')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Maintenance % of cost', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Cost + Maintenance cost', max_digits=10)),
                ('cost_per_part', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Total cost / (Lifecycle × 288)', max_digits=10)),
                ('polybag_cost', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='3.56 / Part per polybag', max_digits=10)),
                ('total_packaging_cost', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Cost per part + Polybag cost', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='core.quote')),
            ],
            options={
                'verbose_name': 'Packaging',
                'verbose_name_plural': 'Packagings',
                'ordering': ['created_at'],
            },
        ),
    ]
