# Generated by Django 4.2.25 on 2025-10-12 18:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_packaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_length', models.DecimalField(decimal_places=2, default=0, help_text='Overall length of transport vehicle', max_digits=10)),
                ('transport_breadth', models.DecimalField(decimal_places=2, default=0, help_text='Overall breadth of transport vehicle', max_digits=10)),
                ('transport_height', models.DecimalField(decimal_places=2, default=0, help_text='Overall height of transport vehicle', max_digits=10)),
                ('trip_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per trip', max_digits=10)),
                ('parts_per_box', models.IntegerField(default=1, help_text='Number of parts per box')),
                ('boxes_on_length', models.IntegerField(default=0, editable=False, help_text='Transport length / Box length (rounded down)')),
                ('boxes_on_breadth', models.IntegerField(default=0, editable=False, help_text='Transport breadth / Box breadth (rounded down)')),
                ('boxes_on_height', models.IntegerField(default=0, editable=False, help_text='Transport height / Box height (rounded down)')),
                ('total_boxes', models.IntegerField(default=0, editable=False, help_text='Boxes on length × breadth × height')),
                ('total_parts_per_trip', models.IntegerField(default=0, editable=False, help_text='Total boxes × Parts per box')),
                ('trip_cost_per_part', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Trip cost / Total parts per trip', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packaging', models.ForeignKey(help_text='Associated packaging type', on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='core.packaging')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='core.quote')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['created_at'],
            },
        ),
    ]
