# Generated by Django 4.2.25 on 2025-10-12 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('quote_created', 'Quote Created'), ('quote_updated', 'Quote Updated'), ('raw_material_added', 'Raw Material Added'), ('raw_material_deleted', 'Raw Material Deleted'), ('moulding_machine_added', 'Moulding Machine Added'), ('moulding_machine_deleted', 'Moulding Machine Deleted'), ('assembly_added', 'Assembly Added'), ('assembly_deleted', 'Assembly Deleted'), ('assembly_rm_added', 'Assembly Raw Material Added'), ('assembly_rm_deleted', 'Assembly Raw Material Deleted'), ('manufacturing_cost_added', 'Manufacturing Cost Added'), ('manufacturing_cost_deleted', 'Manufacturing Cost Deleted'), ('packaging_added', 'Packaging Added'), ('packaging_deleted', 'Packaging Deleted'), ('transport_added', 'Transport Added'), ('transport_deleted', 'Transport Deleted'), ('section_completed', 'Section Completed'), ('manual_entry', 'Manual Entry')], max_length=50)),
                ('description', models.TextField(help_text='Description of the change/activity')),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='timeline_attachments/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='core.quote')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quote Timeline Entry',
                'verbose_name_plural': 'Quote Timeline Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
