# Generated by Django 4.2.25 on 2025-11-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quotetimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='major_version',
            field=models.IntegerField(default=1, help_text='Major version (e.g., 1 in 1.5)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='minor_version',
            field=models.IntegerField(default=0, help_text='Minor version (e.g., 5 in 1.5)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('discarded', 'Discarded')], default='in_progress', max_length=20),
        ),
    ]
