# Generated by Django 4.2.25 on 2025-11-09 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_quote_major_version_quote_minor_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouldingMachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_rate', models.DecimalField(decimal_places=2, default=0, help_text='Shift rate', max_digits=10)),
                ('shift_rate_for_mtc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shift Rate for MTC')),
                ('mtc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MTC Cost')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moulding_machine_types', to=settings.AUTH_USER_MODEL)),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moulding_machine_types', to='core.customergroup')),
            ],
            options={
                'verbose_name': 'Moulding Machine Type',
                'verbose_name_plural': 'Moulding Machine Types',
                'ordering': ['customer_group', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_name', models.CharField(default='', max_length=200)),
                ('raw_material_grade', models.CharField(default='', max_length=100)),
                ('raw_material_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_types', to=settings.AUTH_USER_MODEL)),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_types', to='core.customergroup')),
            ],
            options={
                'verbose_name': 'Material Type',
                'verbose_name_plural': 'Material Types',
                'ordering': ['customer_group', 'raw_material_name'],
                'unique_together': {('customer_group', 'raw_material_name', 'raw_material_grade')},
            },
        ),
    ]
