# Generated by Django 4.2.25 on 2025-11-09 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_mouldingmachinetype_materialtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblytype',
            options={'ordering': ['customer_group', 'name'], 'verbose_name': 'Assembly Type', 'verbose_name_plural': 'Assembly Types'},
        ),
        migrations.AlterModelOptions(
            name='materialgroup',
            options={'ordering': ['customer_group', 'name'], 'verbose_name': 'Material Group', 'verbose_name_plural': 'Material Groups'},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'ordering': ['customer_group', 'name'], 'verbose_name': 'Packaging Type', 'verbose_name_plural': 'Packaging Types'},
        ),
        migrations.AlterUniqueTogether(
            name='materialtype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assemblytype',
            name='customer_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_types', to='core.customergroup'),
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='customer_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_groups', to='core.customergroup'),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='customer_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_types', to='core.customergroup'),
        ),
        migrations.AlterField(
            model_name='assemblytype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assemblytype',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assemblytype',
            name='value',
            field=models.CharField(default='', help_text='Unique identifier/code', max_length=100),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='value',
            field=models.CharField(default='', help_text='Unique identifier/code', max_length=100),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='customer_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_types', to='core.customergroup'),
        ),
        migrations.AlterField(
            model_name='mouldingmachinetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moulding_machine_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mouldingmachinetype',
            name='customer_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moulding_machine_types', to='core.customergroup'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='value',
            field=models.CharField(default='', help_text='Unique identifier/code', max_length=100),
        ),
    ]
