# Generated by Django 4.2.25 on 2025-11-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_assemblytype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='client_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.customergroup'),
        ),
    ]
