# Generated by Django 4.2.25 on 2025-11-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_quote_client_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouldingmachinetype',
            options={'ordering': ['customer_group', 'name'], 'verbose_name': 'Moulding Machine Type', 'verbose_name_plural': 'Moulding Machine Types'},
        ),
        migrations.AddField(
            model_name='mouldingmachinetype',
            name='name',
            field=models.CharField(default='', help_text='Name/identifier for this machine type', max_length=200),
        ),
    ]
