# Generated by Django 4.2.25 on 2025-11-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_mouldingmachinetype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='material_group',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='rm_cost',
        ),
        migrations.AddField(
            model_name='materialtype',
            name='raw_material_code',
            field=models.CharField(default='', max_length=100, verbose_name='RM Code'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='material_type',
            field=models.ForeignKey(blank=True, help_text='Select material type to auto-fill details', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials', to='core.materialtype'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='frozen_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Frozen rate if applicable', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='icc_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ICC percentage', max_digits=5, verbose_name='ICC %'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='process_losses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Process losses cost', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit_of_measurement',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('gm', 'Gram (gm)'), ('ton', 'Ton')], default='kg', max_length=10),
        ),
    ]
