# Generated by Django 4.2.25 on 2025-11-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_rawmaterial_gross_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouldingmachinedetail',
            name='conversion_cost',
        ),
        migrations.RemoveField(
            model_name='mouldingmachinedetail',
            name='number_of_mtc',
        ),
        migrations.RemoveField(
            model_name='mouldingmachinedetail',
            name='number_of_parts_per_shift',
        ),
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='moulding_machine_type',
            field=models.ForeignKey(blank=True, help_text='Select machine type to auto-fill details', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moulding_machines', to='core.mouldingmachinetype'),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='cavity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='machine_tonnage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='shift_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
