# Generated by Django 4.2.25 on 2025-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_mouldingmachinedetail_conversion_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='handling_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed handling charge', max_digits=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit percentage', max_digits=5),
        ),
    ]
