# Generated by Django 4.2.25 on 2025-11-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_quote_handling_charge_quote_profit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='maintenance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maintenance percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='overhead_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overhead percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='rejection_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rejection percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='maintenance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maintenance percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='overhead_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overhead percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='rejection_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rejection percentage', max_digits=5),
        ),
    ]
