# Generated by Django 4.2.25 on 2026-01-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_mouldingmachinedetail_maintenance_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouldingmachinedetail',
            name='mtc_cost',
        ),
        migrations.RemoveField(
            model_name='mouldingmachinetype',
            name='mtc_cost',
        ),
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='mtc_count',
            field=models.IntegerField(default=0, help_text='Number of MTC', verbose_name='MTC Count'),
        ),
        migrations.AddField(
            model_name='mouldingmachinetype',
            name='mtc_count',
            field=models.IntegerField(default=0, help_text='Number of MTC', verbose_name='MTC Count'),
        ),
    ]
