# Generated by Django 4.2.25 on 2026-01-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_mouldingmachinedetail_mtc_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='name',
            field=models.CharField(default='', help_text='Assembly name/identifier', max_length=200),
        ),
    ]
