# Generated by Django 4.2.25 on 2026-01-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_assembly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='inspection_handling_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='inspection_handling_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Inspection + Handling percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='manual_cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Cost for manual assembly', max_digits=18),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='other_cost',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='profit_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Profit percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='rejection_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='rejection_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Rejection percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='total_assembly_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='total_assembly_rm_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='total_manufacturing_printing_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='assemblyrawmaterial',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Cost per unit', max_digits=18),
        ),
        migrations.AlterField(
            model_name='assemblyrawmaterial',
            name='production_weight',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Production weight/amount', max_digits=18),
        ),
        migrations.AlterField(
            model_name='assemblyrawmaterial',
            name='total_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, help_text='(Production Weight × Cost/Unit) / Production Quantity', max_digits=18),
        ),
        migrations.AlterField(
            model_name='manufacturingprintingcost',
            name='cycle_time',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Cycle time in seconds', max_digits=18),
        ),
        migrations.AlterField(
            model_name='manufacturingprintingcost',
            name='mc_rate_per_hour',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Machine rate per hour', max_digits=18, verbose_name='M/C Rate/Hr'),
        ),
        migrations.AlterField(
            model_name='manufacturingprintingcost',
            name='mc_tonnage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Machine tonnage', max_digits=18, verbose_name='M/C Tonnage'),
        ),
        migrations.AlterField(
            model_name='manufacturingprintingcost',
            name='per_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, help_text='(Rate/Hr × Cycle Time) / 3600', max_digits=18),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='raw_material_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='cycle_time',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Cycle time in seconds', max_digits=18),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='efficiency',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Efficiency percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='machine_tonnage',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='maintenance_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Maintenance percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='overhead_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Overhead percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Profit percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='rejection_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Rejection percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='shift_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='shift_rate_for_mtc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='Shift Rate for MTC'),
        ),
        migrations.AlterField(
            model_name='mouldingmachinetype',
            name='shift_rate',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Shift rate', max_digits=18),
        ),
        migrations.AlterField(
            model_name='mouldingmachinetype',
            name='shift_rate_for_mtc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='Shift Rate for MTC'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='breadth',
            field=models.DecimalField(decimal_places=8, default=400, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Base cost', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='cost_per_part',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, help_text='Total cost / (Lifecycle × 288)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='height',
            field=models.DecimalField(decimal_places=8, default=250, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='length',
            field=models.DecimalField(decimal_places=8, default=600, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, help_text='Maintenance % of cost', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='maintenance_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Maintenance percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='polybag_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, help_text='3.56 / Part per polybag', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='polybag_length',
            field=models.DecimalField(decimal_places=8, default=16, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='polybag_width',
            field=models.DecimalField(decimal_places=8, default=20, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='total_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, help_text='Cost + Maintenance cost', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='total_packaging_cost',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, help_text='Cost per part + Polybag cost', max_digits=18),
        ),
        migrations.AlterField(
            model_name='quote',
            name='handling_charge',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Fixed handling charge', max_digits=18),
        ),
        migrations.AlterField(
            model_name='quote',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Profit percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='frozen_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Frozen rate if applicable', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='icc_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='ICC percentage', max_digits=13, verbose_name='ICC %'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='maintenance_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Maintenance percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='overhead_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Overhead percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='part_weight',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='process_losses',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Process losses cost', max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Profit percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='purging_loss_cost',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='rejection_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Rejection percentage', max_digits=13),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='rm_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='RM Rate'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='runner_weight',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_breadth',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Overall breadth of transport vehicle', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_height',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Overall height of transport vehicle', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_length',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Overall length of transport vehicle', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='trip_cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Cost per trip', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='trip_cost_per_part',
            field=models.DecimalField(decimal_places=8, default=0, editable=False, help_text='Trip cost / Total parts per trip', max_digits=18),
        ),
    ]
