# Generated by Django 4.2.25 on 2026-01-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_assembly_inspection_handling_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='breadth',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='cost_per_part',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='height',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='length',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='maintenance_cost',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='polybag_cost',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='total_packaging_cost',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='boxes_on_breadth',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='boxes_on_height',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='boxes_on_length',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='total_boxes',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='total_parts_per_trip',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='trip_cost_per_part',
        ),
        migrations.AddField(
            model_name='packaging',
            name='packaging_breadth',
            field=models.DecimalField(decimal_places=8, default=400, help_text='Packaging breadth (mm)', max_digits=18),
        ),
        migrations.AddField(
            model_name='packaging',
            name='packaging_height',
            field=models.DecimalField(decimal_places=8, default=250, help_text='Packaging height (mm)', max_digits=18),
        ),
        migrations.AddField(
            model_name='packaging',
            name='packaging_length',
            field=models.DecimalField(decimal_places=8, default=600, help_text='Packaging length (mm)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Cost of packaging', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='lifecycle',
            field=models.IntegerField(default=1, help_text='Number of times packaging can be used'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='packaging_type',
            field=models.CharField(choices=[('pp_box', 'PP Box'), ('pp_box_partition', 'PP Box with Partition'), ('cg_box', 'CG Box'), ('bin', 'Bin')], default='pp_box', max_length=20),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='polybag_length',
            field=models.DecimalField(decimal_places=8, default=16, help_text='Polybag length', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='polybag_width',
            field=models.DecimalField(decimal_places=8, default=20, help_text='Polybag width', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='Related packaging', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='core.packaging'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_breadth',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Transport breadth', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_height',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Transport height', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_length',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Transport length', max_digits=18),
        ),
    ]
