# Generated by Django 4.2.25 on 2026-01-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_packaging_breadth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Additional notes or remarks', null=True),
        ),
    ]
