# Generated by Django 4.2.25 on 2026-01-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_assembly_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyrawmaterial',
            name='production_weight',
        ),
    ]
