# Generated by Django 4.2.25 on 2026-01-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_assemblyrawmaterial_production_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='rm_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='RM Rate (per gram)'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_breadth',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Transport breadth (ft)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_height',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Transport height (ft)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_length',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Transport length (ft)', max_digits=18),
        ),
    ]
