# Generated by Django 4.2.25 on 2026-01-11 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_rawmaterial_rm_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='assembly_type',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='inspection_handling_percentage',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='profit_cost',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='rejection_cost',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='total_assembly_cost',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='total_assembly_rm_cost',
        ),
        migrations.RemoveField(
            model_name='assembly',
            name='total_manufacturing_printing_cost',
        ),
        migrations.AlterField(
            model_name='assembly',
            name='assembly_type_config',
            field=models.ForeignKey(blank=True, help_text='Assembly type configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies', to='core.assemblytype'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='inspection_handling_cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Fixed cost for inspection and handling', max_digits=18, verbose_name='Inspection & Handling Cost'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='manual_cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Manual assembly cost (used if automated)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='other_cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Other miscellaneous costs', max_digits=18),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='rejection_percentage',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13),
        ),
    ]
