# Generated by Django 4.2.25 on 2026-01-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_assembly_assembly_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyrawmaterial',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='assemblyrawmaterial',
            name='production_weight',
            field=models.CharField(blank=True, default='', help_text='Optional production weight (text field, not used in calculations)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assemblyrawmaterial',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='assemblyrawmaterial',
            name='production_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assemblyrawmaterial',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('gm', 'Gram (gm)'), ('nos', 'Numbers (nos)'), ('mtr', 'Meter (mtr)')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='frozen_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Frozen rate if applicable (per kg)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='rm_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='RM Rate (per kg)'),
        ),
    ]
