# Generated by Django 4.2.25 on 2026-01-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_assemblyrawmaterial_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'ordering': ['packaging_type', 'name'], 'verbose_name': 'Packaging Type', 'verbose_name_plural': 'Packaging Types'},
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='part_per_polybag',
        ),
        migrations.AddField(
            model_name='packaging',
            name='parts_per_polybag',
            field=models.IntegerField(default=0, help_text='Parts per polybag'),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='default_breadth',
            field=models.DecimalField(decimal_places=8, default=400, help_text='Default packaging breadth (mm)', max_digits=18),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='default_height',
            field=models.DecimalField(decimal_places=8, default=250, help_text='Default packaging height (mm)', max_digits=18),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='default_length',
            field=models.DecimalField(decimal_places=8, default=600, help_text='Default packaging length (mm)', max_digits=18),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='default_polybag_length',
            field=models.DecimalField(decimal_places=8, default=16, help_text='Default polybag length', max_digits=18),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='default_polybag_width',
            field=models.DecimalField(decimal_places=8, default=20, help_text='Default polybag width', max_digits=18),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='packaging_type',
            field=models.CharField(choices=[('pp_box', 'PP Box'), ('pp_box_partition', 'PP Box by Partition'), ('cg_box', 'CG Box'), ('bin', 'Bin'), ('custom', 'Custom')], default='pp_box', max_length=50),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Packaging cost', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='lifecycle',
            field=models.IntegerField(default=0, help_text='Lifecycle count'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='packaging_breadth',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Packaging breadth (mm)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='packaging_height',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Packaging height (mm)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='packaging_length',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Packaging length (mm)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='packaging_type',
            field=models.ForeignKey(blank=True, help_text='Select packaging type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packagings', to='core.packagingtype'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='polybag_length',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Polybag length', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='polybag_width',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Polybag width', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='customer_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_types', to='core.customergroup'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='name',
            field=models.CharField(help_text='Packaging type name', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='packagingtype',
            unique_together={('customer_group', 'name')},
        ),
        migrations.RemoveField(
            model_name='packagingtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='packagingtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packagingtype',
            name='value',
        ),
    ]
