# Generated by Django 4.2.7 on 2026-01-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_packagingtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='part_weight',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Part weight in selected unit', max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='process_losses',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Process losses in percent', max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='purging_loss_cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Purging losses in percent', max_digits=18),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='runner_weight',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Runner weight in selected unit', max_digits=18),
        ),
    ]
