# Generated by Django 4.2.7 on 2026-01-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_rawmaterial_part_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='other_rm_cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Additional fixed cost for this raw material', max_digits=18),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='other_rm_cost_description',
            field=models.TextField(blank=True, help_text='Description of what the other RM cost pertains to'),
        ),
    ]
