# Generated by Django 4.2.7 on 2026-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rawmaterial_other_rm_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='other_cost_description',
            field=models.TextField(blank=True, help_text='Description of what the other cost pertains to'),
        ),
    ]
