# Generated by Django 4.2.25 on 2026-01-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_assembly_other_cost_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='parts_per_polybag',
        ),
        migrations.AddField(
            model_name='packaging',
            name='packaging_category',
            field=models.CharField(choices=[('polybag', 'Polybag'), ('box', 'Box')], default='box', help_text='Select polybag or box', max_length=20),
        ),
        migrations.AddField(
            model_name='packaging',
            name='parts_per_packaging',
            field=models.IntegerField(default=0, help_text='Parts per packaging unit'),
        ),
        migrations.AddField(
            model_name='packaging',
            name='polybags_per_kg',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Number of polybags in 1 kg', max_digits=18),
        ),
        migrations.AddField(
            model_name='packaging',
            name='rate_per_kg',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Rate per kg (for polybag)', max_digits=18),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='default_polybags_per_kg',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Default number of polybags per kg', max_digits=18),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='default_rate_per_kg',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Default rate per kg (for polybag)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Base cost for box', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='polybag_length',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Polybag length in inches', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='polybag_width',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Polybag width in inches', max_digits=18),
        ),
    ]
