# Generated by Django 4.2.25 on 2026-01-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_packaging_parts_per_polybag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'ordering': ['customer_group', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='packagingtype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='packaging_category',
            field=models.CharField(choices=[('polybag', 'Polybag'), ('box', 'Box')], default='box', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='customer_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_types', to='core.customergroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='default_breadth',
            field=models.DecimalField(decimal_places=8, default=400, help_text='Default breadth in mm', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='default_height',
            field=models.DecimalField(decimal_places=8, default=250, help_text='Default height in mm', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='default_length',
            field=models.DecimalField(decimal_places=8, default=600, help_text='Default length in mm', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='default_polybag_length',
            field=models.DecimalField(decimal_places=8, default=16, help_text='Default polybag length in inches', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='default_polybag_width',
            field=models.DecimalField(decimal_places=8, default=20, help_text='Default polybag width in inches', max_digits=18),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='packagingtype',
            name='packaging_type',
        ),
        migrations.RemoveField(
            model_name='packagingtype',
            name='updated_at',
        ),
    ]
