# Generated by Django 4.2.25 on 2026-02-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_packagingtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='frozen_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Frozen rate if applicable (per kg) and per pc for uom pcs', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='rm_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='RM Rate (per kg) and per pc for uom pcs'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit_of_measurement',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('gm', 'Gram (gm)'), ('ton', 'Ton'), ('pcs', 'Pcs')], default='kg', max_length=10),
        ),
    ]
