# Generated by Django 4.2.25 on 2026-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_rawmaterial_frozen_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyrawmaterial',
            name='production_quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
