# Generated by Django 4.2.25 on 2026-03-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_assemblyrawmaterial_production_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyrawmaterial',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('gm', 'Gram (gm)'), ('nos', 'Numbers (nos)'), ('mtr', 'Meter (mtr)'), ('cm', 'Centimeter (cm)'), ('mm', 'Millimeter (mm)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('sq in', 'Square inch (sq in)'), ('sq cm', 'Square cm (sq cm)'), ('sq ft', 'Square ft (sq ft)')], default='kg', max_length=10),
        ),
    ]
