# Generated by Django 4.2.25 on 2026-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_assemblyrawmaterial_unit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assemblytype',
            constraint=models.UniqueConstraint(fields=('name', 'customer_group'), name='unique_assembly_type_name_customer_group'),
        ),
        migrations.AddConstraint(
            model_name='materialtype',
            constraint=models.UniqueConstraint(fields=('raw_material_name', 'customer_group'), name='unique_material_type_raw_material_name_customer_group'),
        ),
        migrations.AddConstraint(
            model_name='mouldingmachinetype',
            constraint=models.UniqueConstraint(fields=('name', 'customer_group'), name='unique_moulding_machine_type_name_customer_group'),
        ),
        migrations.AddConstraint(
            model_name='packagingtype',
            constraint=models.UniqueConstraint(fields=('name', 'customer_group'), name='unique_packaging_type_name_customer_group'),
        ),
    ]
