# Generated by Django 4.2.25 on 2026-04-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_assemblytype_unique_assembly_type_name_customer_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblytype',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Additional notes or remarks', null=True),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Additional notes or remarks', null=True),
        ),
        migrations.AddField(
            model_name='mouldingmachinetype',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Additional notes or remarks', null=True),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Additional notes or remarks', null=True),
        ),
    ]
