# Generated by Django 4.2.25 on 2026-04-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_assemblytype_remarks_materialtype_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='maintenance_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether maintenance is percentage or fixed value', max_length=10),
        ),
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='overhead_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether overhead is percentage or fixed value', max_length=10),
        ),
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='profit_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether profit is percentage or fixed value', max_length=10),
        ),
        migrations.AddField(
            model_name='mouldingmachinedetail',
            name='rejection_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether rejection is percentage or fixed value', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='icc_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether ICC is percentage or fixed value', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='maintenance_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether maintenance is percentage or fixed value', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='overhead_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether overhead is percentage or fixed value', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='profit_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether profit is percentage or fixed value', max_length=10),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='rejection_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether rejection is percentage or fixed value', max_length=10),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='maintenance_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Maintenance percentage or fixed value', max_digits=13),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='overhead_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Overhead percentage or fixed value', max_digits=13),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Profit percentage or fixed value', max_digits=13),
        ),
        migrations.AlterField(
            model_name='mouldingmachinedetail',
            name='rejection_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Rejection percentage or fixed value', max_digits=13),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='icc_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='ICC percentage or fixed value', max_digits=13, verbose_name='ICC %'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='maintenance_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Maintenance percentage or fixed value', max_digits=13),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='overhead_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Overhead percentage or fixed value', max_digits=13),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Profit percentage or fixed value', max_digits=13),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='rejection_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Rejection percentage or fixed value', max_digits=13),
        ),
    ]
