# Generated by Django 4.2.25 on 2026-04-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_mouldingmachinedetail_maintenance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='profit_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether profit is percentage or fixed value', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Profit percentage or fixed value', max_digits=13),
        ),
    ]
