# Generated by Django 4.2.25 on 2026-04-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_quote_profit_type_alter_quote_profit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='profit_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether profit is percentage or fixed value', max_length=10),
        ),
        migrations.AddField(
            model_name='assembly',
            name='rejection_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Value')], default='percentage', help_text='Whether rejection is percentage or fixed value', max_length=10),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Profit percentage or fixed value', max_digits=13),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='rejection_percentage',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Rejection percentage or fixed value', max_digits=13),
        ),
    ]
