# Generated by Django 4.2.25 on 2026-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_assembly_profit_type_assembly_rejection_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='manual_cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Manually uploaded cost', max_digits=18),
        ),
        migrations.AddField(
            model_name='transport',
            name='manual_cost',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Manually uploaded cost', max_digits=18),
        ),
    ]
